<?php

use Illuminate\Database\Seeder;
use App\AdministrativeUbication;

class AdministrativeUbicationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        AdministrativeUbication::create(['ubicacion_administrativa'=>'ÓRGANO SUPERIOR','nivel'=>'1']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Despacho Superior','nivel'=>'2']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'ÓRGANOS SUSTANTIVOS','nivel'=>'1']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Viceministerio de Inversión y Compentencia','nivel'=>'2']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Dirección de Servicios al Comercio y la Inversión','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Política Industrial','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Verificación y Seguimiento','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Dirección del Sistema Nacional de Calidad','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Comisión Guatemalteca de Normas','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Oficina Guatemalteca de Acreditación','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Centro Nacional de Metrología','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Laboratorio Nacional de Metrología','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Inspección y Verificación en Materia de Metrología Legal','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Comisión Nacional de Reglamentación Técnica','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Dirección de Promoción de la Competencia','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Análisis e Información','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Promoción a la Competencia','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Dirección de Atención y Asistencia al Consumidor','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Verificación y Vigilancia','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Promoción y Asesoría al Consumidor y Proveedor','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Servicios al Consumidor','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Coordinación de Sedes','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento Legal','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Auditoría Interna de la DIACO','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Programa Nacional de la Competitividad','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Viceministerio de Asustos Registrales','nivel'=>'2']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Registro del Mercado de Valores y Mercancías','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Registro Mercantil General de la República','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Operaciones Registrales','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Laboratorio Nacional de Metrología','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Empresas Mercantiles','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Sociedades Nuevas','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Auxiliares del Comercio','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Modificaciones','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Certificaciones','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Coordinación de Sedes','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Archivo General y Escaneo','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Soporte de Sistemas','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Servicios al Usuario','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento Legal','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Análisis','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Informes','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Registro de la Propiedad Intelectual','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Marcas y Otros Signos Distintivos','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Examen Técnico','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Inscripciones, Errores Materiales y Certificaciones','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Renovaciones','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Traspasos','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Recepción y Archivo','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Atención al Usuario','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Patentes y Diseños Industriales','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Examen Técnico','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Recepción, Archivo y Anualidades','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Derechos de Auytor y Derechos Conexos','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Registro de Obras','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Gestión Colectiva','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Registro de Garantías Mobiliarias','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Atención a Usuarios','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección Jurídica','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Soporte Sistema de Garantías Mobiliarias','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Registro de Prestadores de Servicios de Certificación','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Viceministerio de Integración y Comercio Exterior','nivel'=>'2']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Dirección de Política de Comercio Exterior','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Negociaciones','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Integración Centroamericana','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Apoyo a la Misión de la Organización Mundial del Comercio','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Dirección de Administración del Comercio Exterior','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Contingentes Arancelarios','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Verificación de Origen','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Medidas Arancelarias y no Arancelarias','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Acceso a Mercados','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Obstáculos Técnicos al Comercio, Medio Ambiente y Laboral','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Medidas Sanitarias y Fitosanitarias','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Defensa Comercial','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Análisis de Prácticas Desleales de Comercio','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Solución de Controversias','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Programa de apoyo al Comercio Exterior y la Integración','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Misión permanente de Guatemala ante la Organización Mundial del Comercio','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Viceministerio de Desarrollo de la Microempresa, Pequeña y Mediana Empresa','nivel'=>'2']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Dirección de Servicios Financieros Empresariales','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Unidad de Apoyo al Consejo Nacional para el Desarrollo de la MIPYME','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Programas y Proyectos Financieros','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Fortalecimiento Financiero','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Programas y Proyectos','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Gestión de Fideicomisos','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección Financiera de Fideicomisos','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Supervición y Control de Fideicomisos','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Registro de Entres de Micro finanzas sin Fines de Lucro','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Soporte SISREM','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Análisis Financiero de Microfinanzas','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Dirección de Servicios de Desarrollo Empresarial','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Articulación Productiva y de Inserción de Cooperativas','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Articulación Productiva','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Inserción a Cooperativas','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Coordinación con Centros de Atención MIPYME y de Emprendimiento','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sedes de Dinamización Económina','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Centros de Atención PROMIPYME','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Promoción Comercial de la MIPYME','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Comercialización Artesanal','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Inteligencia de Mercado y Cadenas de Valor','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Empresarialidad','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Ferias y Encuentros Comerciales','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Fortalecimiento al Emprendimiento','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Redes de Emprendimiento','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Cultura y Sistema Educativo','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Atracción Financiera','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Monitoreo y Evaluación del Emprendimiento','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Centros de Formación para el Emprendimiento','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'ÓRGANOS ADMINISTRATIVOS Y FINANCIEROS','nivel'=>'1']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Viceministerio Administrativo y Financiero','nivel'=>'2']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Dirección Administrativa','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Administración Interna','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Servicios Generales','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Inventario','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Almacén','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Seguridad','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección Administrativa Financiera','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Infraestructura y Mantenimiento de Instalaciones','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Infraestructura','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Mantenimiento de instalaciones','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Dirección de Adquisiciones y Contrataciones','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Gestión de Compras Directas y Baja Cuantía','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Eventos de Cotizaciones y Licitaciones','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Dirección Financiera','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Tesorería','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Contabilidad','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Presupuesto','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Dirección de Recursos Humanos','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Dotación de Recursos Humanos','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Contratación y Administración','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Contrataciones','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Nóminas','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Capacitación y Desarrollo','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Capacitación','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Desarrollo Humano','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Bienestar y de Relaciones Laborales','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Relaciones Laborales','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Bienestar Laboral','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Dirección de Desarrollo Institucional','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de fortalecimiento Institucional','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Coordinación de Procesos y Gestión de Calidad','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'ÓRGANOS DE APOYO TÉCNICO','nivel'=>'1']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Tecnologías de la Información','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Desarrollo de Sistemas','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Soporte Informático','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Operaciones y de Seguridad Informática','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Planificación, Proyectos y Cooperación','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Planificación y Control de Gestión ','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Deparamento de Gestión de Proyectos','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Cooperación','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Asuntos Jurídicos','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Asuntos Administrativos','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Procesos Administrativos y Judiciales','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Política y Análisis Económico','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Análisis e Investigación','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Estadísticas','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Secretaría General','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Análisis, Resoluciones y Notificaciones','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Análisis y Resoluciones','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Notificaciones','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento Administrativo y de Información Pública','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección Administrativa','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Sección de Información Pública','nivel'=>'5']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Comunicación Social','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Comunicación','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Relaciones Públicas','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Género, Pueblos Indígenas y Personas con Capacidades Especiales','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'ÓRGANO DE CONTROL INTERNO','nivel'=>'1']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Auditoría Interna','nivel'=>'3']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Ficalización Interna','nivel'=>'4']);
        AdministrativeUbication::create(['ubicacion_administrativa'=>'Departamento de Auditoría de Sistemas de Información','nivel'=>'4']);
    }
}
